#!/usr/bin/env python3
"""Build Swift lesson text from the reviewed content source. No runtime network/resources."""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def quoted(value):
    return json.dumps(value, ensure_ascii=False)


def build():
    with (ROOT / 'docs/curriculum-v2.csv').open(encoding='utf-8-sig') as handle:
        outline = {int(row['display_order']): row for row in csv.DictReader(handle)}
    authored = {}
    for line in (ROOT / 'data/study-course/lessons.txt').read_text().splitlines():
        if not line or line.startswith('#'):
            continue
        fields = line.split('|')
        assert len(fields) == 8, fields[0]
        number = int(fields[0])
        assert number not in authored
        quizzes = [field.split('~') for field in fields[3:]]
        assert all(len(q) == 3 and all(q) for q in quizzes), number
        authored[number] = (fields[1], fields[2], quizzes)
    assert set(authored) == {i for i in range(1, 101) if i % 10}
    result = ['// Generated by scripts/build-study-course.py. Edit data/study-course/lessons.txt.',
              'import Foundation', '', 'enum StudyContent {',
              '    static func makeLessons() -> [StudyLesson] {', '        var lessons: [StudyLesson] = []']
    for number in range(1, 101):
        row = outline[number]
        application = re.sub(r'(^G[＋，]|；K，)', lambda m: '实战任务：' if m.start() == 0 else '。检查目标：', row['exercise_and_acceptance'])
        if number % 10:
            lecture, example, quizzes = authored[number]
        else:
            lecture = '这一课把本单元的知识放在一起。先独立回答，再检查提示；把答错的原因写成下一盘能执行的动作。综合题会回顾已学内容，不代表新的棋形题库。'
            example = application + '。题目全做完会记录“学过”；独立答对达到标准会显示“本轮达标”。对局与个人复盘另行记录，不以胜负判过关。'
            start = number - 9
            quizzes = [authored[start + i % 9][2][(number // 10 + i) % 5] for i in range(10)]
        result.append('        do {')
        result.append('            var exercises: [StudyExercise] = [')
        for index, (prompt, correct, wrong) in enumerate(quizzes):
            # Reproducible, varied choice order. No implicit "A is always correct" shortcut.
            order = ((number * 17 + index * 13) ^ (number >> 1)) % 2
            options = [correct, wrong] if order == 0 else [wrong, correct]
            result.append('                StudyExercise(id: %s, prompt: %s, explanation: %s, options: [%s], answer: %s),' % (
                quoted(f'study-{number:03d}-q{index+1}'), quoted(prompt + '？'),
                quoted('正确理解：' + correct + '。' + example), ', '.join(map(quoted, options)), order))
        result += ['            ]', f'            let boardTask = StudyDiagrams.task(for: {number})',
                   '            if let boardTask { exercises.append(boardTask) }']
        # Demo solutions are presented before exercises, as examples, not counted as unseen mastery.
        result.append('            lessons.append(StudyLesson(id: %d, title: %s, objective: %s, explanation: %s, example: %s, application: %s, exercises: exercises, demonstration: boardTask, wuID: %s))' % (
            number, quoted(row['title']), quoted(row['learning_objective']), quoted(lecture), quoted(example),
            quoted(application), {10:'0',51:'1',54:'2',56:'3',67:'4',77:'5',89:'6',94:'7',95:'1',96:'5'}.get(number,'nil')))
        result.append('        }')
    result += ['        return lessons', '    }', '}', '']
    output = ROOT / 'ios/GoKit/Core/StudyContent.swift'
    output.write_text('\n'.join(result))
    print(f'Built {output.relative_to(ROOT)}: 100 lessons, 450 authored choices + 100 cumulative-review choices.')


if __name__ == '__main__':
    build()
